# Generated by Django 5.2.1 on 2025-05-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_generation', '0002_chapter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='knowledge_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
