# Generated by Django 5.2.1 on 2025-05-18 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_generation', '0004_question_exercise_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userknowledge',
            unique_together={('user',)},
        ),
        migrations.AddField(
            model_name='userknowledge',
            name='knowledge_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userknowledge',
            name='unknown_list',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='userknowledge',
            name='knowledge_level',
        ),
        migrations.RemoveField(
            model_name='userknowledge',
            name='topic',
        ),
    ]
