# Generated by Django 5.2.1 on 2025-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_generation', '0005_alter_userknowledge_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
