# Generated by Django 5.2.1 on 2025-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_generation', '0006_exercise_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
