# Generated by Django 5.2.1 on 2025-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_generation', '0008_chapter_score_exam_score_exercise_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
